export const FARM_DATA_LOADING = "FARM_DATA_LOADING";
export const LOAD_FARM_DATA_ERROR = "LOAD_FARM_DATA_ERROR";
export const SET_FARM_DATA = "SET_FARM_DATA";
export const SET_SELECTED_FARM_DATA = "SET_SELECTED_FARM_DATA";

export const PRECIPITATION_DATA_LOADING = "PRECIPITATION_DATA_LOADING";
export const LOAD_PRECIPITATION_DATA_ERROR = "LOAD_PRECIPITATION_DATA_ERROR";
export const SET_PRECIPITATION_DATA = "SET_PRECIPITATION_DATA";

export const NDVI_DATA_LOADING = "NDVI_DATA_LOADING";
export const LOAD_NDVI_DATA_ERROR = "LOAD_NDVI_DATA_ERROR";
export const SET_NDVI_DATA = "SET_NDVI_DATA";

export const GET_ERRORS = "GET_ERRORS";
export const USER_LOADING = "USER_LOADING";
export const SET_CURRENT_USER = "SET_CURRENT_USER";
